# ==============================================================================
#  run_phaseB_shard.jl — the post-campaign MMS batch, sharded over independent
#  OS processes.
#
#  WHY INDEPENDENT PROCESSES, not Distributed/pmap: measured in the vertical-basis
#  campaign (MMS_VBASIS_CAMPAIGN.md §8.1) — three pmap launches each completed ONE
#  study in >4 h while the identical calls ran at full speed in a plain process,
#  and worker prints are relayed through a master whose stdout is never flushed,
#  so slow is indistinguishable from hung. Each shard here writes its OWN csv and
#  flushes every row.
#
#  SJF ORDERING: the deliverable is coverage, so cheap studies run first
#  (rule 43). Contiguous slicing of a cost-sorted queue is the WORST partition;
#  studies are dealt round-robin instead.
#
#  USAGE:  julia --project=. examples/local_mms/run_phaseB_shard.jl <shard> <nshard>
# ==============================================================================
using GridapBALFEM, Printf, Dates

const SHARD  = parse(Int, ARGS[1])
const NSHARD = parse(Int, ARGS[2])
#  ⚠ THIS MUST MATCH `OUT` IN supervise_phaseB2.sh. The 2026-09-11 output
#  reorganisation moved the batch to output/local/mms/phaseB and updated the
#  supervisor but not this line, so the runner was pointing at a directory that
#  no longer exists. Consequences, had it been launched: the resume scan below
#  reads CSVs from OUT, so `done` would have been EMPTY and all 34 finished
#  Phase-B studies would have re-run; and `exhausted_NN` would have been written
#  where the supervisor never looks, so it would spin forever.
const OUT    = joinpath(@__DIR__, "..", "..", "output", "local", "mms", "phaseB")
mkpath(OUT)
#  ⚠ SCHEMA v2 GETS ITS OWN FILE. The 2026-09-11 widening added five per-level
#  columns (nx_list, e_eta_list, e_u_list, pw_eta_list, pw_u_list), taking a row
#  from 22 to 27 fields — but the header is only written when the file is NEW
#  (`newfile` below), so appending to a pre-existing Phase-B csv would file
#  27-field rows under a 22-field header: a file whose header lies about its own
#  contents. Versioning the NAME leaves every historical row untouched and gives
#  the new batch a correct header. `shard_*.csv` still globs both (the
#  supervisor's row count), and the resume scan reads every .csv in OUT, so the
#  38 finished studies are still recognised as done.
const CSV = joinpath(OUT, @sprintf("shard_%02d_v2.csv", SHARD))

MODELS = Dict(
 1=>(regime=:linear,    flat_bed=true,  nlp=:none),
 2=>(regime=:linear,    flat_bed=false, nlp=:none),
 3=>(regime=:nonlinear, flat_bed=true,  nlp=:none),
 4=>(regime=:nonlinear, flat_bed=false, nlp=:none),
 5=>(regime=:nonlinear, flat_bed=true,  nlp=:native),
 6=>(regime=:nonlinear, flat_bed=false, nlp=:native),
 7=>(regime=:nonlinear, flat_bed=true,  nlp=:full),
 8=>(regime=:nonlinear, flat_bed=false, nlp=:full))

#  ---- the queue. `cost` is a rough ordering key only (SJF). ------------------
struct Job; task::String; basis::String; M::Int; p::Int; model::Int
       p_u::Int; domain::Symbol; levels::Int; nx0::Int; a_eta::Float64; cost::Int; end

#  ---- DIAGNOSTICS + OUTPUT DESTINATION (2026-09-11, PLANNED_CAMPAIGNS.md §4b/§4c) -----
#  ~20 samples over a 100-step run: enough to see a trend, too few to cost anything.
const DIAG_EVERY = parse(Int, get(ENV, "PHASEB_DIAG_EVERY", "5"))

#  A job carries its destination rather than having it inferred afterwards. The
#  tree is  <model>/<pair>/nx<N>/, and run_conv_study appends the nx<N> level.
const MODEL_DIR = Dict(
    1 => "linear_flat_none",     2 => "linear_var_none",
    3 => "nonlinear_flat_none",  4 => "nonlinear_var_none",
    5 => "nonlinear_flat_native",6 => "nonlinear_var_native",
    7 => "nonlinear_flat_full",  8 => "nonlinear_var_full")

#  ⚠ 1-D studies land in the tracked campaign tree; everything else keeps a flat
#  per-task directory, because that tree is defined for 1-D convergence only.
outdir_for(j::Job) = j.domain === :d1 && haskey(MODEL_DIR, j.model) ?
    joinpath("output","local_1d","mms_convergence_campaigns",
             MODEL_DIR[j.model], "Q$(j.p_u)Q$(j.p_u-1)") :
    joinpath("output","local","mms","phaseB_runs", j.task,
             "M$(j.model)_Q$(j.p_u)Q$(j.p_u-1)_$(j.domain)")

jobs = Job[]
#  TASK 7 — P1LFE-4 extended spatial ladder to nx=128 (1-D, Q3/Q2)
for m in 1:6
    push!(jobs, Job("T7_extladder","P1LFE-4",4,1,m,3,:d1,5,8,0.8, 40))
end
#  TASK 8 — the :full pair with the FIXED driver, at a solvable amplitude
#  ⚠ P2LFE-2 dropped 2026-09-08 for the same reason as in TASK 10 below: its
#  mesh is DEFAULT_CBDY_P[(2,2)], generated by the superseded objective.
for (nm,M,p) in (("P1LFE-2",2,1),("P2LFE-1",1,2),("P1LFE-3",3,1),("P1LFE-4",4,1))
    for m in (7,8)
        push!(jobs, Job("T8_full_projection",nm,M,p,m,3,:d1,4,8,0.4, 60))
    end
end
#  TASK 9 — tier 2: the horizontal pairings. 1-D on a LONG ladder (this is what
#  actually answers the pre-asymptotic question, and it is affordable); 2-D at the
#  scheduled 4 levels.
for pu in (2,3,4), m in (1,3)
    push!(jobs, Job("T9_tier2_1d","P1LFE-2",2,1,m,pu,:d1,5,8,0.8, 30))
    push!(jobs, Job("T9_tier2_2d","P1LFE-2",2,1,m,pu,:d2,4,8,0.8, 90))
end
#  TASK 9b — Q4/Q3 in 1-D RE-SPECIFIED. The original T9 ran it to nx=128, where
#  Q4/Q3's fifth-order convergence puts e_eta and e_u at 9e-11 and 1.4e-10 -- the
#  DOUBLE-PRECISION FLOOR. A saturated error and a genuine low rate produce the
#  same slope, so the measured p_u (1.08 and 2.51) is UNMEASURABLE, not a defect.
#  The fix is a SHORTER ladder, not a longer one: stopping at nx=32 leaves
#  e_u ~ 8e-08, about 800x the floor, which is readable. Three levels give only
#  two pairwise rates -- that is the most Q4/Q3 supports in double precision at
#  this domain size, and it is why the campaign's advice is to check error
#  MAGNITUDE before trusting any fine-level high-order rate.
for m in (1,3)
    #  cost 95 = the HIGHEST in the queue, deliberately, even though these are the
    #  CHEAPEST jobs here (3 levels to nx=32). SJF would sort them first, but the
    #  queue is cost-sorted and shards are dealt round-robin over that order, so
    #  inserting anywhere but the END renumbers every later job and moves it to a
    #  different shard -- while workers launched under the old numbering are still
    #  mid-study on jobs that would then be claimed by a second shard. Appending
    #  keeps every existing index, and therefore every ownership, unchanged.
    push!(jobs, Job("T9b_tier2_1d_short","P1LFE-2",2,1,m,4,:d1,3,8,0.8, 95))
end
#  TASK 10 — high-order vertical bases on the NEW optimised nodes
#  ⚠ P2LFE-2 IS CANCELLED (2026-09-08) AND IS NOT TO BE REGENERATED.
#  It is the ONLY basis here whose mesh comes from the optimiser rather than
#  from Yang & Liu's published table: resolve_cbdy sends p≥2 to DEFAULT_CBDY_P,
#  whose (2,2) entry [0, 0.8298, 1] was produced by the PRE-2026-09-08 objective
#  (Kronecker median population, C_g² in E_cg, abs on E_shoal). A convergence
#  study is only as meaningful as the mesh it refines on, so those runs measure
#  a superseded design. The 6 rows already written are void — see
#  output/local/mms/phaseB/INVALID_P2LFE-2.md.
#  Every other basis in this file is unaffected: p=1 resolves to DEFAULT_CBDY
#  (published values, untouched), and P2LFE-1 is M=1 — a single element with no
#  free interface, so no optimiser output enters it.
#  ⚠ Do NOT re-add this by regenerating DEFAULT_CBDY_P: the band Ω for p≥2 comes
#  from VOPT_KAPPA, a constant FITTED to the old optimiser's own output and of
#  unverified physical standing. A p≥2 mesh needs a defensible Ω first.
for (nm,M,p) in (("P2LFE-1",1,2),), m in 1:6
    push!(jobs, Job("T10_highorder_newnodes",nm,M,p,m,3,:d1,4,8,0.8, 35))
end

#  ---- CAMPAIGN C (2026-09-11, PLANNED_CAMPAIGNS.md §5.1) ---------------------
#  APPENDED AT THE END, AT THE HIGHEST COST, DELIBERATELY. The queue is
#  cost-sorted then dealt round-robin, so an insertion in the MIDDLE renumbers
#  every later job and reassigns its owning shard — which is how the two 2-D
#  Q4/Q3 jobs ended up owned by shards whose `exhausted` markers predated the
#  edit and were never launched (§4). Costs 96/97 exceed every existing cost
#  (max 95), and `sort!` is stable, so indices 1..34 are untouched.
#
#  Ladder is PAIRING-DEPENDENT (§0):
#      Q2Q1, Q3Q2 -> levels=5, nx0=4  ->  nx = 4, 8, 16, 32, 64
#      Q4Q3       -> levels=4, nx0=4  ->  nx = 4, 8, 16, 32   (64 sits on the
#                                         ~1e-10 algebraic floor and saturates)
levels_for(pu) = pu == 4 ? 4 : 5

#  C1 — the four models tier 2 never covered. T9/T9b swept only models 1 and 3,
#  both flat-bed and both :none, so every existing pairing result is blind to
#  bathymetry and to the 𝓝 blocks (rule 4: a flat-bed study CANNOT exercise ∇h
#  code). Models 5 and 6 are :native, the production tier.
for pu in (2,3,4), m in (2,4,5,6)
    push!(jobs, Job("C1_pairings_1d","P1LFE-2",2,1,m,pu,:d1,levels_for(pu),4,0.8, 96))
end

#  C2 — RE-RUN the two models tier 2 did cover. Their per-level errors were never
#  persisted (verbose=false + save_every=0) and are NOT recoverable; they must not
#  be reconstructed from the recorded rate either, since e(nx/2)=e(nx)·2^p assumes
#  the very quantity being measured (§2B).
for pu in (2,3,4), m in (1,3)
    push!(jobs, Job("C2_rerun_1d","P1LFE-2",2,1,m,pu,:d1,levels_for(pu),4,0.8, 97))
end

#  ⚠ NO 2-D (decided 2026-09-11): 12 solver runs per model per domain is too
#  expensive to take on now. 2-D Q4/Q3 has never been run and remains the largest
#  single gap; when it is picked up it MUST be re-specified short (levels=4,
#  nx0=4) and never launched on the original nx0=8 spec (~20 h/study, saturates).

#  ---- CAMPAIGN C3 (2026-09-11) — the 2-D Q4/Q3 tier ---------------------------
#  2-D Q4/Q3 HAS NEVER BEEN RUN and is the largest single gap in the pairing
#  study (PLANNED_CAMPAIGNS.md §1). Taken up now because Campaign C's queue is
#  fully in flight and the machine is otherwise idle.
#
#  ⚠ SHORT LADDER, MANDATORY. The original 2-D spec carried levels=4 from nx0=8
#  (nx to 64) at ~20 h per study, and it SATURATES for the same reason the 1-D
#  long ladder did — Q4/Q3's fifth-order convergence puts the fine end on the
#  ~1e-10 algebraic floor, where a saturated error and a genuine low rate are
#  indistinguishable (§0). nx0=4 with levels=4 gives nx = 4,8,16,32.
#
#  Appended at cost 98 — above Campaign C's 96/97 — so indices 1..52 and every
#  existing shard ownership are untouched (the §4 renumbering hazard).
for m in 1:6
    push!(jobs, Job("C3_tier2_2d","P1LFE-2",2,1,m,4,:d2,4,4,0.8, 98))
end

sort!(jobs; by = j -> j.cost)                    # SJF
mine = [j for (i,j) in enumerate(jobs) if (i-1) % NSHARD == SHARD]   # round-robin

#  ---- RESUME (rule 41: bound worker lifetime; a restart must cost one JIT, not
#  the whole shard). A study is DONE if any shard csv already carries its key.
#  Without this a recycled worker re-runs finished studies, which is exactly what
#  made killing a degraded process expensive the first time round.
jobkey(j) = (j.task, j.basis, j.model, j.p_u, string(j.domain))
done = Set{Tuple{String,String,Int,Int,String}}()
for f in readdir(OUT; join=true)
    endswith(f, ".csv") || continue
    for (i,ln) in enumerate(eachline(f))
        i == 1 && continue
        c = split(ln, ","); length(c) < 20 && continue
        push!(done, (c[1], c[2], parse(Int,c[5]), parse(Int,c[9]), c[10]))
    end
end
#  ---- CANCELLED IN PLACE, NOT DELETED (2026-09-11) ---------------------------
#  T9_tier2_2d at p_u=4 is the 2-D Q4/Q3 LONG ladder (levels=4, nx0=8 -> nx to
#  64). PLANNED_CAMPAIGNS.md §1: "when it is picked up it must be re-specified
#  short; NEVER launch it as it stands" — ~20 h/study, and the fine end sits on
#  the ~1e-10 algebraic floor where a saturated error and a genuine low rate are
#  indistinguishable. C3_tier2_2d (nx0=4) IS that re-specification and supersedes
#  it. Measured while it briefly ran: 12.1 GB RSS on one worker at 3h21m.
#
#  ⚠ FILTERED HERE, AFTER the round-robin assignment, and the Job is LEFT IN THE
#  LIST — deleting it would renumber every later job and reassign its owning
#  shard, which is the §4 hazard that stranded these very jobs the first time.
#  This is also why they came back: clearing every `exhausted` marker (needed so
#  C3 could launch) un-stranded them, and at cost 90 they sort AHEAD of Campaign
#  C's 96/97. A marker is not a cancellation; this is.
cancelled(j) = j.task == "T9_tier2_2d" && j.p_u == 4
todo = [j for j in mine if !(jobkey(j) in done) && !cancelled(j)]
@printf("[shard %02d] %d assigned, %d already done, %d to run\n",
        SHARD, length(mine), length(mine)-length(todo), length(todo)); flush(stdout)

#  Exit after MAX_STUDIES so the supervisor gets a FRESH process. Measured in the
#  vertical-basis campaign: RSS grew 1.5 -> 4.6 GB and CPU fell to 7-14 % on
#  long-lived Julia+Gridap workers. Bounding lifetime is the fix; resume makes it cheap.
const MAX_STUDIES = parse(Int, get(ENV, "PHASEB_MAX_STUDIES", "2"))
mine = todo[1:min(end, MAX_STUDIES)]
#  Leave a marker so the supervisor stops relaunching an exhausted shard. Work
#  only ever shrinks, so an exhausted id stays exhausted. Without this the
#  supervisor -- which picks the LOWEST free id -- relaunched one finished shard
#  217 times and never reached the ids that still had jobs.
if isempty(mine)
    touch(joinpath(OUT, @sprintf("exhausted_%02d", SHARD)))
    println("[shard $SHARD] nothing to do"); exit(0)
end

newfile = !isfile(CSV)
open(CSV, "a") do io
    #  ⚠ THE PAIRWISE SEQUENCE IS NOW PERSISTED, not just its last element.
    #  Rules 32/33: a rising sequence with the error still dropping is
    #  PRE-ASYMPTOTIC; a flat sequence with a stalled error is SATURATED — and the
    #  fitted slope cannot tell them apart. Keeping only pw_*[end] and fit_* is what
    #  forced the 2026-09-11 re-run of two whole models. `nx_list`, `e_eta_list`,
    #  `e_u_list`, `pw_eta_list`, `pw_u_list` are ';'-separated so the CSV stays flat.
    newfile && println(io,"task,basis,M,p,model,regime,flat_bed,nl_pressure,p_u,domain,levels,a_eta,",
               "pw_eta,pw_u,fit_eta,fit_u,e_eta_fine,e_u_fine,nx_fine,status,seconds,note,",
               "nx_list,e_eta_list,e_u_list,pw_eta_list,pw_u_list")
    flush(io)
    for (n,j) in enumerate(mine)
        mo = MODELS[j.model]
        @printf("[shard %02d] %d/%d  %s %s M%d %s Q%d/Q%d %s\n",
                SHARD,n,length(mine),j.task,j.basis,j.model,string(mo.nlp),j.p_u,j.p_u-1,
                string(j.domain)); flush(stdout)
        t0 = time(); status="OK"; note=""
        local r
        try
            #  ⚠ ny0 FOLLOWS THE DOMAIN ASPECT, it does not default to 8.
            #  The MMS domain is Lx=1.7, Ly=1.1, so ny0=8 against nx0=4 would give
            #  3.1:1 cells and 2.7x the DOFs at the fine end — real money for a
            #  pairing already measured at >5 GB/worker. ny0 = round(nx0*Ly/Lx)
            #  keeps cells at 1.16:1 across the whole ladder (rule 22).
            #  Unused for :d1, where ny is pinned at ny_1d=1 (rule 12).
            ny0_j = j.domain === :d2 ? max(2, round(Int, j.nx0 * 1.1/1.7)) : 8
            r = run_conv_study(p_u=j.p_u, domain=j.domain, mode=:static,
                               levels=j.levels, nx0=j.nx0, ny0=ny0_j,
                               M=j.M, p_vert=j.p, a_eta=j.a_eta,
                               regime=mo.regime, flat_bed=mo.flat_bed,
                               nl_pressure=mo.nlp,
                               a_b = mo.flat_bed ? 0.0 : 0.2,
                               #  §4c diagnostic policy: ~20 samples per run, a real
                               #  SolverMonitor (so t_solve / nl_iters stop reading 0),
                               #  per-level diagnostics.csv under the job's output dir.
                               output_dir = outdir_for(j),
                               diag_every = DIAG_EVERY, diag_csv = true,
                               monitor_factory = () -> SolverMonitor(),
                               #  ⚠ verbose=false is what discarded the per-level errors
                               #  of the first campaign. It stays TRUE from now on.
                               verbose=true)
        catch e
            status="ERROR"; note=first(split(sprint(showerror,e),"\n"))
            note=replace(note, ","=>";")[1:min(end,120)]
            r=nothing
        end
        dt = round(time()-t0; digits=1)
        if r === nothing
            @printf(io,"%s,%s,%d,%d,%d,%s,%s,%s,%d,%s,%d,%.3f,,,,,,,%s,%.1f,%s,,,,,\n",
                    j.task,j.basis,j.M,j.p,j.model,mo.regime,mo.flat_bed,mo.nlp,
                    j.p_u,j.domain,j.levels,j.a_eta,status,dt,note)
        else
            pwe = length(r.pw_eta)>0 ? r.pw_eta[end] : NaN
            pwu = length(r.pw_u)>0   ? r.pw_u[end]   : NaN
            nxl = join([j.nx0*2^l for l in 0:(j.levels-1)], ";")
            eel = join([@sprintf("%.6e",x) for x in r.e_eta], ";")
            eul = join([@sprintf("%.6e",x) for x in r.e_u],   ";")
            pel = join([@sprintf("%.4f",x) for x in r.pw_eta], ";")
            pul = join([@sprintf("%.4f",x) for x in r.pw_u],   ";")
            @printf(io,"%s,%s,%d,%d,%d,%s,%s,%s,%d,%s,%d,%.3f,%.4f,%.4f,%.4f,%.4f,%.6e,%.6e,%d,%s,%.1f,%s,%s,%s,%s,%s,%s\n",
                    j.task,j.basis,j.M,j.p,j.model,mo.regime,mo.flat_bed,mo.nlp,
                    j.p_u,j.domain,j.levels,j.a_eta,pwe,pwu,r.fit_eta,r.fit_u,
                    r.e_eta[end],r.e_u[end],j.nx0*2^(j.levels-1),status,dt,note,
                    nxl,eel,eul,pel,pul)
        end
        flush(io)
    end
end
@printf("[shard %02d] DONE %d studies\n", SHARD, length(mine)); flush(stdout)
